version: '3.8'
services:
  db:
    container_name: postgresdb
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=databaseuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=esportsdb
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
